[package]
name = "fakie"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
dashmap = "6"
hickory-resolver = "0.25"
pingora = { version = "0.5", features = ["lb", "rustls"] }
termcolor = "1"
url = "2"
